name: smart_college
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.17.0
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.0
  fl_chart: ^0.50.1
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.2.2
  flutter_image_compress: ^2.3.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  image: ^3.0.1
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/logo.png
    - assets/images/man.png
    - assets/images/emoji.png
    - assets/images/wind.png
    
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf